<?php

return array(
	'iconType' => 'font',
	'iconMap' => array(
		'about' => 'fas fa-search',
		'back' => 'fas fa-chevron-left',
		'backup' => 'far fa-save',
		'chat' => 'far fa-comments',
		'closed' => 'fas fa-caret-right',
		'command' => 'far fa-edit',
		'command_del' => 'far fa-minus-square',
		'command_new' => 'far fa-plus-square',
		'config' => 'fas fa-wrench',
		'console' => 'far fa-list-alt',
		'create' => 'far fa-plus-square',
		'delete' => 'far fa-trash-alt',
		'file' => 'far fa-file',
		'help' => 'far fa-life-ring',
		'key_del' => 'far fa-minus-square',
		'key_new' => 'far fa-plus-square',
		'mysql' => 'fas fa-database',
		'mysql_del' => 'far fa-minus-square',
		'mysql_new' => 'far fa-plus-square',
		'mysql_passwd' => 'fas fa-key',
		'open' => 'fas fa-caret-down',
		'operations' => 'fas fa-cogs',
		'params' => 'fas fa-tools',
		'player' => 'fas fa-gamepad',
		'player_del' => 'fas fa-user-minus',
		'player_new' => 'fas fa-user-plus',
		'plugin' => 'fas fa-toolbox',
		'restore' => 'fas fa-redo-alt',
		'resume' => 'fas fa-play',
		'schedule' => 'far fa-clock',
		'schedule_del' => 'far fa-minus-square',
		'schedule_new' => 'far fa-plus-square',
		'server' => 'fas fa-server',
		'statistics' => 'fas fa-tachometer-alt',
		'status' => 'far fa-check-circle',
		'suspend' => 'fas fa-pause',
		'user' => 'fas fa-user',
		'user_del' => 'fas fa-user-minus',
		'user_new' => 'fas fa-user-plus',
		'update' => 'fas fa-arrow-up',
		'welcome' => 'far fa-hand-spock',
	),
);
